# Generated by Django 6.0.4 on 2026-04-27 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='antenarfid',
            name='ativacao_expira_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='antenarfid',
            name='online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='antenarfid',
            name='ultimo_ping',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificacaoinconsistencia',
            name='resolvida_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timelineevento',
            name='metadados',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='AuditoriaJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracao_segundos', models.PositiveIntegerField(default=5)),
                ('status', models.CharField(choices=[('iniciado', 'Iniciado'), ('concluido', 'Concluido')], default='iniciado', max_length=20)),
                ('iniciado_em', models.DateTimeField(auto_now_add=True)),
                ('finaliza_em', models.DateTimeField()),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditoriaLeitorStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('energizado', 'Energizado'), ('encerrado', 'Encerrado')], default='energizado', max_length=20)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('antena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='core.antenarfid')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leitores', to='core.auditoriajob')),
            ],
        ),
    ]
