# Generated by Django 6.0.4 on 2026-05-02 16:23

from django.db import migrations, models


def normalize_removed_discard_types(apps, schema_editor):
    AntenaRFID = apps.get_model("core", "AntenaRFID")
    TimelineEvento = apps.get_model("core", "TimelineEvento")
    AntenaRFID.objects.filter(tipo=3).update(tipo=2)
    TimelineEvento.objects.filter(tipo="descarte").update(tipo="baixa")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_antenarfid_ativacao_expira_em_antenarfid_online_and_more'),
    ]

    operations = [
        migrations.RunPython(normalize_removed_discard_types, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='antenarfid',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Destino'), (2, 'Fluxo')]),
        ),
        migrations.AlterField(
            model_name='timelineevento',
            name='tipo',
            field=models.CharField(choices=[('movimentacao', 'Movimentacao'), ('inconsistencia', 'Inconsistencia'), ('rastro', 'Rastro'), ('baixa', 'Baixa patrimonial'), ('sistema', 'Sistema')], max_length=20),
        ),
    ]
