# Generated by Django 6.0.4 on 2026-05-02 16:23

from django.db import migrations, models


def normalize_removed_discard_readings(apps, schema_editor):
    LeituraRFID = apps.get_model("core", "LeituraRFID")
    LeituraRFID.objects.filter(classificacao="descarte").update(classificacao="fluxo")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_antenarfid_tipo_alter_timelineevento_tipo'),
    ]

    operations = [
        migrations.RunPython(normalize_removed_discard_readings, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='leiturarfid',
            name='classificacao',
            field=models.CharField(choices=[('destino', 'Destino'), ('fluxo', 'Fluxo')], max_length=20),
        ),
    ]
