# Generated by Django 6.0.4 on 2026-05-03 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_leiturarfid_classificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacaoinconsistencia',
            name='metadados',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notificacaoinconsistencia',
            name='tag_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='notificacaoinconsistencia',
            name='tipo',
            field=models.CharField(choices=[('local_divergente', 'Local divergente'), ('nao_encontrado', 'Nao encontrado'), ('tag_desconhecida', 'Tag desconhecida')], default='local_divergente', max_length=30),
        ),
        migrations.AlterField(
            model_name='notificacaoinconsistencia',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inconsistencias', to='core.itempatrimonial'),
        ),
    ]
